version: '3.8'

services:
  team-honor-board:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Монтируем папки для сохранения данных
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - GO_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/members"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
